Flujo creacion de profesionales
jose-andres-ucr/nutrimetas pull request #53
Opened 2024-06-30 18:38 UTC by FabianCalvoAlcazar

Ahora existe un rol de admin que es capaz de crear profesionales
Se implementó el login para el admin
Se crea dicho rol en la bd

2024-06-30 18:57 UTC, suehtemorp requested changes

2024-06-30 18:57 UTC, suehtemorp commented on app/(app)/(admin)/_layout.tsx
> +  }
Se puede hacer un redirect a la pantalla de `sign-in` si el rol no es administrador mediante este condicional.

Es decir:
```
if (session === undefined || session.role !== "admin") {
	return <Redirect href="/sign-in" />
} 
```

2024-07-03 10:25 UTC, suehtemorp commented on app/(app)/(admin)/_layout.tsx
> +  }
Listo, me gustan los cambios!

2024-07-03 10:25 UTC, suehtemorp approved these changes

2024-07-04 02:00 UTC, lizethcorrales approved these changes

2024-07-04 02:30 UTC, merged